### ISSUE TITLE
Fix URL for iperf3 sources

### ISSUE THREAD

**Issue by bmah888** [Wind-River/vxworks7-layer-for-iperf#3]
Hello and thanks for making iperf3 work on VXworks!

The `README.md` file here advises that users download iperf3 from the iperf.fr Web site.  Please be aware that iperf.fr is not affiliated in any way with the Energy Sciences Network (ESnet), who is the sponsoring organization for iperf3 development.  (We do not believe the parties behind iperf.fr have malicious intent, but they play no role in the development of iperf3.)  In addition, iperf.fr does not appear to be maintained for at least a year and a half, judging by the software versions they have available.  Newer versions of iperf3 have been released since then, which contain bug fixes, security fixes, and new features.  The site maintainer has so far been unresponsive to our inquiries.

The official documentation site for iperf3 is:  http://software.es.net/iperf/
The official download site for iperf 3 is http://downloads.es.net/pub/iperf/

I highly recommend that you change your documentation to point to the official sources for iperf3.

Thanks,

Bruce Mah
Software Engineering Group, ESnet

**Comment by pbi-wind** [comment]
README.md and Makefile have been updated.

Thanks,

Peng Bi, Sr. Engineering Manager
WIND RIVER
